POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "Md.Mashfiqur Rahman",
  "email": "mashfiqurrr@gmail.com",
  "password": "sayburg"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "mashfiqurrr@gmail.com",
  "password": "sayburg"
}

###
GET http://localhost:3000/user/new_access_token


###
POST http://localhost:3000/blog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc2hmaXF1cnJyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTE1NTM4MSwiZXhwIjoxNjE5MTY2MTgxfQ.zFHuRs1q_pvI_lOl4QvWOVpn6BfW86xCuR2IhucUi-w
Content-Type: application/json

{
  "title": "Beyond Grammar % Spelling",
  "description": "From grammar and spelling to style and tone, Grammarly helps you eliminate errors and find the perfect words to express yourself.",
  "tags": "60823fa5441f512db8944204"
}

###
GET http://localhost:3000/blog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc2hmaXF1cnJyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTE1NTM4MSwiZXhwIjoxNjE5MTY2MTgxfQ.zFHuRs1q_pvI_lOl4QvWOVpn6BfW86xCuR2IhucUi-w



###
GET  http://localhost:3000/blog/608259d1ffef5609f497ef24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc2hmaXF1cnJyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTE1NTM4MSwiZXhwIjoxNjE5MTY2MTgxfQ.zFHuRs1q_pvI_lOl4QvWOVpn6BfW86xCuR2IhucUi-w


###
PATCH  http://localhost:3000/blog/60825accffef5609f497ef27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc2hmaXF1cnJyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTE1NTM4MSwiZXhwIjoxNjE5MTY2MTgxfQ.zFHuRs1q_pvI_lOl4QvWOVpn6BfW86xCuR2IhucUi-w
Content-Type: application/json 

{
  "title": "Earn Money",
  "description": "From grammar and spelling to style and tone, Grammarly helps you eliminate errors and find the perfect words to express yourself.",
  "tags": "6081377bfe044708a8d68077,60813794fe044708a8d68079,608137a0fe044708a8d6807a"
}




###
DELETE  http://localhost:3000/blog/60825accffef5609f497ef27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc2hmaXF1cnJyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTE1NTM4MSwiZXhwIjoxNjE5MTY2MTgxfQ.zFHuRs1q_pvI_lOl4QvWOVpn6BfW86xCuR2IhucUi-w




###
POST http://localhost:3000/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hc2hmaXF1cnJyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTE1NTM4MSwiZXhwIjoxNjE5MTY2MTgxfQ.zFHuRs1q_pvI_lOl4QvWOVpn6BfW86xCuR2IhucUi-w
Content-Type: application/json

{
  "remark": "wooh! This is a nice blog.",
  "blogId": "60825accffef5609f497ef27"
}
###

